services:
  crypexlog_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./sqlite-data:/app/prisma/sqlite-data
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: on-failure
    depends_on:
      - migration_service

  migration_service:
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - ./sqlite-data:/app/prisma/sqlite-data
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    command: ["npm", "run", "setup"]

  caddy_web_server:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - crypexlog_app

volumes:
  sqlite-data:
  caddy_data:
  caddy_config:
